import React, { useState, useEffect } from 'react';
import {
  HeartPulse,
  Filter,
  RefreshCw,
  ListChecks,
  Stethoscope,
  Info,
  ShieldCheck,
  ChevronLeft,
  ChevronRight,
  UserCheck,
} from 'lucide-react';
import { RecommendationResponse, TabType } from '../types';
import { api } from '../api';

interface RecommendationsViewProps {
  setActiveTab: (tab: TabType) => void;
  currentUser: any;
  onOpenAuthModal: () => void;
}

export const RecommendationsView: React.FC<RecommendationsViewProps> = ({
  setActiveTab,
  currentUser,
  onOpenAuthModal,
}) => {
  const [items, setItems] = useState<RecommendationResponse[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [pageSize] = useState(10);
  const [diseaseFilter, setDiseaseFilter] = useState<string>('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchRecommendations = () => {
    if (!currentUser) {
      setLoading(false);
      return;
    }
    setLoading(true);
    setError(null);

    api
      .getRecommendations(page, pageSize, diseaseFilter || undefined)
      .then((res) => {
        setItems(res.items || []);
        setTotal(res.total || 0);
      })
      .catch((err) => {
        setError(err.message || 'Failed to fetch recommendations');
      })
      .finally(() => {
        setLoading(false);
      });
  };

  useEffect(() => {
    fetchRecommendations();
  }, [currentUser, page, diseaseFilter]);

  if (!currentUser) {
    return (
      <div className="flex-1 overflow-y-auto p-8 flex flex-col items-center justify-center text-center space-y-4 select-none">
        <div className="w-16 h-16 rounded-full bg-emerald-50 text-emerald-600 flex items-center justify-center">
          <UserCheck className="w-8 h-8" />
        </div>
        <h2 className="text-2xl font-bold text-slate-900">Authentication Required</h2>
        <p className="text-sm text-slate-600 max-w-md">
          Sign in to view your personalized health guidance and disease risk recommendations generated by our deterministic rules engine.
        </p>
        <button
          onClick={onOpenAuthModal}
          className="px-6 py-2.5 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl text-xs font-semibold shadow-sm transition-all"
        >
          Sign In / Register
        </button>
      </div>
    );
  }

  return (
    <div className="flex-1 overflow-y-auto p-6 md:p-8 space-y-6 select-none">
      {/* Header Banner */}
      <div className="bg-white rounded-[2rem] border border-slate-200 p-6 shadow-xs flex flex-col md:flex-row justify-between md:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 tracking-tight flex items-center gap-2">
            <HeartPulse className="w-6 h-6 text-emerald-600" />
            <span>Personalized Health Recommendations</span>
          </h1>
          <p className="text-xs text-slate-600 mt-1">
            Review deterministic health guidance generated from your scientific disease screening assessments.
          </p>
        </div>

        {/* Filter Bar */}
        <div className="flex items-center gap-2">
          <Filter className="w-4 h-4 text-slate-400" />
          <select
            value={diseaseFilter}
            onChange={(e) => {
              setDiseaseFilter(e.target.value);
              setPage(1);
            }}
            className="text-xs border border-slate-200 rounded-xl p-2 bg-slate-50 font-medium"
          >
            <option value="">All Diseases</option>
            <option value="diabetes">Diabetes</option>
            <option value="cardiovascular">Cardiovascular</option>
            <option value="cancer">Cancer</option>
          </select>
        </div>
      </div>

      {/* Content Section */}
      {loading ? (
        <div className="py-12 flex justify-center items-center text-slate-500 text-xs font-medium">
          <RefreshCw className="w-5 h-5 animate-spin text-emerald-600 mr-2" /> Loading recommendations...
        </div>
      ) : error ? (
        <div className="p-4 bg-red-50 text-red-700 text-xs rounded-xl border border-red-200">
          {error}
        </div>
      ) : items.length === 0 ? (
        <div className="bg-white rounded-[2rem] border border-slate-200 p-12 text-center text-slate-400 text-xs space-y-2">
          <p>No health recommendations found for your account.</p>
          <button
            onClick={() => setActiveTab('diseases')}
            className="text-xs text-emerald-600 font-semibold hover:underline"
          >
            Submit an assessment to generate guidance
          </button>
        </div>
      ) : (
        <div className="space-y-6">
          {items.map((rec) => (
            <div
              key={rec.id || Math.random()}
              className="bg-white rounded-[2rem] border border-slate-200 p-6 shadow-xs space-y-5"
            >
              <div className="flex items-center justify-between border-b border-slate-100 pb-3">
                <div className="flex items-center gap-2">
                  <span className="text-xs font-bold uppercase tracking-wider text-emerald-800 bg-emerald-50 px-3 py-1 rounded-full border border-emerald-200">
                    {rec.disease} Recommendation
                  </span>
                  <span className="text-[11px] text-slate-400 font-mono">
                    Rule Set: {rec.rule_set_version}
                  </span>
                </div>
                {rec.created_at && (
                  <span className="text-xs text-slate-500 font-mono">
                    {new Date(rec.created_at).toLocaleDateString()}{' '}
                    {new Date(rec.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                  </span>
                )}
              </div>

              {/* Summary */}
              <div className="p-4 bg-slate-50 border border-slate-200/80 rounded-2xl">
                <p className="text-sm font-semibold text-slate-800 leading-relaxed">{rec.summary}</p>
              </div>

              {/* Priority Actions & Monitoring */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
                {rec.priority_actions && rec.priority_actions.length > 0 && (
                  <div className="p-4 bg-rose-50/50 border border-rose-100 rounded-2xl space-y-2">
                    <div className="flex items-center gap-2 font-bold text-rose-900">
                      <ListChecks className="w-4 h-4 text-rose-600" />
                      <span>Priority Actions</span>
                    </div>
                    <ul className="space-y-1.5 list-disc list-inside text-rose-950">
                      {rec.priority_actions.map((act, idx) => (
                        <li key={idx}>{act}</li>
                      ))}
                    </ul>
                  </div>
                )}

                {rec.monitoring && rec.monitoring.length > 0 && (
                  <div className="p-4 bg-blue-50/50 border border-blue-100 rounded-2xl space-y-2">
                    <div className="flex items-center gap-2 font-bold text-blue-900">
                      <Stethoscope className="w-4 h-4 text-blue-600" />
                      <span>Monitoring Guidance</span>
                    </div>
                    <ul className="space-y-1.5 list-disc list-inside text-blue-950">
                      {rec.monitoring.map((item, idx) => (
                        <li key={idx}>{item}</li>
                      ))}
                    </ul>
                  </div>
                )}
              </div>

              {/* Professional Care & Emergency Guidance */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
                <div className="p-4 bg-white border border-slate-200 rounded-2xl space-y-1">
                  <span className="font-bold text-slate-900 block">Professional Follow-Up</span>
                  <p className="text-slate-600 leading-relaxed">{rec.professional_follow_up}</p>
                </div>
                <div className="p-4 bg-white border border-slate-200 rounded-2xl space-y-1">
                  <span className="font-bold text-amber-900 block">When to Seek Urgent Care</span>
                  <p className="text-amber-800 leading-relaxed">{rec.when_to_seek_care}</p>
                </div>
              </div>

              {/* Factors */}
              {rec.factors && rec.factors.length > 0 && (
                <div className="p-4 bg-slate-50 border border-slate-200 rounded-2xl space-y-2 text-xs">
                  <span className="font-bold text-slate-900 flex items-center gap-1.5">
                    <Info className="w-4 h-4 text-slate-500" />
                    <span>Contributing Factors</span>
                  </span>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 pt-1">
                    {rec.factors.map((f, idx) => (
                      <div key={idx} className="p-2.5 bg-white border border-slate-200 rounded-xl text-slate-700">
                        <span className="font-semibold block text-slate-900">{f.name}</span>
                        <span className="text-[11px] text-slate-500">{f.summary}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Disclaimer */}
              <div className="p-3 bg-amber-50/60 border border-amber-200/60 rounded-xl text-[11px] text-amber-800 italic">
                {rec.disclaimer}
              </div>
            </div>
          ))}

          {/* Pagination */}
          {total > pageSize && (
            <div className="flex items-center justify-between pt-4 border-t border-slate-200 text-xs text-slate-500">
              <span>
                Showing {((page - 1) * pageSize) + 1} to {Math.min(page * pageSize, total)} of {total} recommendations
              </span>
              <div className="flex items-center gap-2">
                <button
                  onClick={() => setPage((p) => Math.max(1, p - 1))}
                  disabled={page === 1}
                  className="p-1.5 border border-slate-200 rounded-lg hover:bg-slate-50 disabled:opacity-40"
                >
                  <ChevronLeft className="w-4 h-4" />
                </button>
                <span className="font-semibold text-slate-700">{page}</span>
                <button
                  onClick={() => setPage((p) => (p * pageSize < total ? p + 1 : p))}
                  disabled={page * pageSize >= total}
                  className="p-1.5 border border-slate-200 rounded-lg hover:bg-slate-50 disabled:opacity-40"
                >
                  <ChevronRight className="w-4 h-4" />
                </button>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
};
