"""Backend ML Service connecting FastAPI endpoints to packaged ModelArtifacts and Explainability.

Authoritative Single Source of Truth for Model Registry and Cross-Disease Inference Isolation.
"""
import logging
import time
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
from fastapi import HTTPException, status

from app.schemas.api import (
    AuditMetadata,
    ExplanationContribution,
    ExplanationResult,
    InferenceRequest,
    InferenceResponse,
)
from ml.artifacts import ModelArtifact, load_artifact
from ml.exceptions import ModelError, ValidationError
from ml.explainability import explanation_service
from ml.preprocessing import RAW_FEATURE_NAMES

logger = logging.getLogger(__name__)

# Canonical Authoritative Model Definitions (51 verified models across 3 diseases)
CANONICAL_MODELS: dict[str, dict[str, Any]] = {
    # =========================================================================
    # DIABETES MELLITUS (19 Models)
    # =========================================================================
    # Production Winner (Phase H Optimization)
    "diabetes_rf_opt_v1": {
        "model_id": "diabetes_rf_opt_v1",
        "disease": "diabetes",
        "display_name": "Random Forest (Optimized)",
        "family": "classical",
        "model_type": "random_forest",
        "version": "v2.0_optimized",
        "artifact_id": "diabetes_rf_opt_v1",
        "artifact_path": "models/classical/diabetes_rf_opt_v1.joblib",
        "manifest_path": "models/classical/diabetes_rf_opt_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": True,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 8,
        "classical_feature_count": 11,
        "quantum_feature_count": None,
        "dataset_version": "v3.0",
        "pipeline_version": "v2.0",
        "score_semantics": "calibrated_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": "Optimized Random Forest maximizing PR-AUC (0.7195) and Sensitivity (77.78%) with probability calibration on 80/20 holdout.",
        "selection_metric": "PR-AUC=0.7195, ROC-AUC=0.8230",
    },
    "diabetes_gb_opt_v1": {
        "model_id": "diabetes_gb_opt_v1",
        "disease": "diabetes",
        "display_name": "Gradient Boosting (Optimized)",
        "family": "classical",
        "model_type": "gradient_boosting",
        "version": "v2.0_optimized",
        "artifact_id": "diabetes_gb_opt_v1",
        "artifact_path": "models/classical/diabetes_gb_opt_v1.joblib",
        "manifest_path": "models/classical/diabetes_gb_opt_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 8,
        "classical_feature_count": 11,
        "quantum_feature_count": None,
        "dataset_version": "v3.0",
        "pipeline_version": "v2.0",
        "score_semantics": "calibrated_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "diabetes_xgb_opt_v1": {
        "model_id": "diabetes_xgb_opt_v1",
        "disease": "diabetes",
        "display_name": "XGBoost (Optimized)",
        "family": "classical",
        "model_type": "xgboost",
        "version": "v2.0_optimized",
        "artifact_id": "diabetes_xgb_opt_v1",
        "artifact_path": "models/classical/diabetes_xgb_opt_v1.joblib",
        "manifest_path": "models/classical/diabetes_xgb_opt_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 8,
        "classical_feature_count": 11,
        "quantum_feature_count": None,
        "dataset_version": "v3.0",
        "pipeline_version": "v2.0",
        "score_semantics": "calibrated_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "diabetes_soft_voting_opt_v1": {
        "model_id": "diabetes_soft_voting_opt_v1",
        "disease": "diabetes",
        "display_name": "Soft Voting Ensemble (Optimized)",
        "family": "classical",
        "model_type": "soft_voting",
        "version": "v2.0_optimized",
        "artifact_id": "diabetes_soft_voting_opt_v1",
        "artifact_path": "models/classical/diabetes_soft_voting_opt_v1.joblib",
        "manifest_path": "models/classical/diabetes_soft_voting_opt_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 8,
        "classical_feature_count": 11,
        "quantum_feature_count": None,
        "dataset_version": "v3.0",
        "pipeline_version": "v2.0",
        "score_semantics": "ensemble_vote_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "logistic_regression_v3": {
        "model_id": "logistic_regression_v3",
        "disease": "diabetes",
        "display_name": "Logistic Regression (v3.0)",
        "family": "classical",
        "model_type": "logistic_regression",
        "version": "v3.0",
        "artifact_id": "logistic_regression_v3",
        "artifact_path": "models/classical/logistic_regression_v3.joblib",
        "manifest_path": "models/classical/logistic_regression_v3_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 8,
        "classical_feature_count": 11,
        "quantum_feature_count": None,
        "dataset_version": "v3.0",
        "pipeline_version": "v2.0",
        "score_semantics": "calibrated_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "svm_v3": {
        "model_id": "svm_v3",
        "disease": "diabetes",
        "display_name": "Support Vector Machine (RBF v3.0)",
        "family": "classical",
        "model_type": "svm",
        "version": "v3.0",
        "artifact_id": "svm_v3",
        "artifact_path": "models/classical/svm_v3.joblib",
        "manifest_path": "models/classical/svm_v3_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 8,
        "classical_feature_count": 11,
        "quantum_feature_count": None,
        "dataset_version": "v3.0",
        "pipeline_version": "v2.0",
        "score_semantics": "calibrated_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "random_forest_v3": {
        "model_id": "random_forest_v3",
        "disease": "diabetes",
        "display_name": "Random Forest (v3.0)",
        "family": "classical",
        "model_type": "random_forest",
        "version": "v3.0",
        "artifact_id": "random_forest_v3",
        "artifact_path": "models/classical/random_forest_v3.joblib",
        "manifest_path": "models/classical/random_forest_v3_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 8,
        "classical_feature_count": 11,
        "quantum_feature_count": None,
        "dataset_version": "v3.0",
        "pipeline_version": "v2.0",
        "score_semantics": "ensemble_vote_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "xgboost_v3": {
        "model_id": "xgboost_v3",
        "disease": "diabetes",
        "display_name": "XGBoost (v3.0)",
        "family": "classical",
        "model_type": "xgboost",
        "version": "v3.0",
        "artifact_id": "xgboost_v3",
        "artifact_path": "models/classical/xgboost_v3.joblib",
        "manifest_path": "models/classical/xgboost_v3_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 8,
        "classical_feature_count": 11,
        "quantum_feature_count": None,
        "dataset_version": "v3.0",
        "pipeline_version": "v2.0",
        "score_semantics": "ensemble_vote_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "qsvc_v3": {
        "model_id": "qsvc_v3",
        "disease": "diabetes",
        "display_name": "Quantum Support Vector Classifier (QSVC-4Q)",
        "family": "quantum",
        "model_type": "qsvc",
        "version": "v3.0",
        "artifact_id": "qsvc_v3",
        "artifact_path": "models/quantum/qsvc_v3.joblib",
        "manifest_path": "models/quantum/qsvc_v3_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": True,
        "quantum": True,
        "qubit_count": 4,
        "raw_feature_count": 8,
        "classical_feature_count": 11,
        "quantum_feature_count": 4,
        "dataset_version": "v3.0",
        "pipeline_version": "v2.0",
        "score_semantics": "uncalibrated_quantum_decision_score",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "vqc_v3": {
        "model_id": "vqc_v3",
        "disease": "diabetes",
        "display_name": "Variational Quantum Classifier (VQC-4Q)",
        "family": "quantum",
        "model_type": "vqc",
        "version": "v3.0",
        "artifact_id": "vqc_v3",
        "artifact_path": "models/quantum/vqc_v3.joblib",
        "manifest_path": "models/quantum/vqc_v3_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": True,
        "quantum": True,
        "qubit_count": 4,
        "raw_feature_count": 8,
        "classical_feature_count": 11,
        "quantum_feature_count": 4,
        "dataset_version": "v3.0",
        "pipeline_version": "v2.0",
        "score_semantics": "uncalibrated_quantum_decision_score",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "qsvc_6q_v1": {
        "model_id": "qsvc_6q_v1",
        "disease": "diabetes",
        "display_name": "Quantum Support Vector Classifier (QSVC-6Q)",
        "family": "quantum",
        "model_type": "qsvc",
        "version": "v1.0",
        "artifact_id": "qsvc_6q_v1",
        "artifact_path": "models/quantum/qsvc_6q_v1.joblib",
        "manifest_path": "models/quantum/qsvc_6q_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": True,
        "quantum": True,
        "qubit_count": 6,
        "raw_feature_count": 8,
        "classical_feature_count": 11,
        "quantum_feature_count": 6,
        "dataset_version": "v3.0",
        "pipeline_version": "v2.0",
        "score_semantics": "uncalibrated_quantum_decision_score",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "vqc_6q_v1": {
        "model_id": "vqc_6q_v1",
        "disease": "diabetes",
        "display_name": "Variational Quantum Classifier (VQC-6Q)",
        "family": "quantum",
        "model_type": "vqc",
        "version": "v1.0",
        "artifact_id": "vqc_6q_v1",
        "artifact_path": "models/quantum/vqc_6q_v1.joblib",
        "manifest_path": "models/quantum/vqc_6q_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": True,
        "quantum": True,
        "qubit_count": 6,
        "raw_feature_count": 8,
        "classical_feature_count": 11,
        "quantum_feature_count": 6,
        "dataset_version": "v3.0",
        "pipeline_version": "v2.0",
        "score_semantics": "uncalibrated_quantum_decision_score",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "qsvc_8q_v1": {
        "model_id": "qsvc_8q_v1",
        "disease": "diabetes",
        "display_name": "Quantum Support Vector Classifier (QSVC-8Q)",
        "family": "quantum",
        "model_type": "qsvc",
        "version": "v1.0",
        "artifact_id": "qsvc_8q_v1",
        "artifact_path": "models/quantum/qsvc_8q_v1.joblib",
        "manifest_path": "models/quantum/qsvc_8q_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": True,
        "quantum": True,
        "qubit_count": 8,
        "raw_feature_count": 8,
        "classical_feature_count": 11,
        "quantum_feature_count": 8,
        "dataset_version": "v3.0",
        "pipeline_version": "v2.0",
        "score_semantics": "uncalibrated_quantum_decision_score",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "vqc_8q_v1": {
        "model_id": "vqc_8q_v1",
        "disease": "diabetes",
        "display_name": "Variational Quantum Classifier (VQC-8Q)",
        "family": "quantum",
        "model_type": "vqc",
        "version": "v1.0",
        "artifact_id": "vqc_8q_v1",
        "artifact_path": "models/quantum/vqc_8q_v1.joblib",
        "manifest_path": "models/quantum/vqc_8q_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": True,
        "quantum": True,
        "qubit_count": 8,
        "raw_feature_count": 8,
        "classical_feature_count": 11,
        "quantum_feature_count": 8,
        "dataset_version": "v3.0",
        "pipeline_version": "v2.0",
        "score_semantics": "uncalibrated_quantum_decision_score",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "linear_svm_v1": {
        "model_id": "linear_svm_v1",
        "disease": "diabetes",
        "display_name": "Support Vector Machine (Linear)",
        "family": "classical",
        "model_type": "linear_svm",
        "version": "v1.0",
        "artifact_id": "linear_svm_v1",
        "artifact_path": "models/classical/linear_svm_v1.joblib",
        "manifest_path": "models/classical/linear_svm_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 8,
        "classical_feature_count": 11,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v2.0",
        "score_semantics": "calibrated_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "knn_v1": {
        "model_id": "knn_v1",
        "disease": "diabetes",
        "display_name": "K-Nearest Neighbors",
        "family": "classical",
        "model_type": "knn",
        "version": "v1.0",
        "artifact_id": "knn_v1",
        "artifact_path": "models/classical/knn_v1.joblib",
        "manifest_path": "models/classical/knn_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 8,
        "classical_feature_count": 11,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v2.0",
        "score_semantics": "ensemble_vote_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "decision_tree_v1": {
        "model_id": "decision_tree_v1",
        "disease": "diabetes",
        "display_name": "Decision Tree",
        "family": "classical",
        "model_type": "decision_tree",
        "version": "v1.0",
        "artifact_id": "decision_tree_v1",
        "artifact_path": "models/classical/decision_tree_v1.joblib",
        "manifest_path": "models/classical/decision_tree_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 8,
        "classical_feature_count": 11,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v2.0",
        "score_semantics": "ensemble_vote_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "extra_trees_v1": {
        "model_id": "extra_trees_v1",
        "disease": "diabetes",
        "display_name": "Extra Trees",
        "family": "classical",
        "model_type": "extra_trees",
        "version": "v1.0",
        "artifact_id": "extra_trees_v1",
        "artifact_path": "models/classical/extra_trees_v1.joblib",
        "manifest_path": "models/classical/extra_trees_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 8,
        "classical_feature_count": 11,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v2.0",
        "score_semantics": "ensemble_vote_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "gradient_boosting_v1": {
        "model_id": "gradient_boosting_v1",
        "disease": "diabetes",
        "display_name": "Gradient Boosting",
        "family": "classical",
        "model_type": "gradient_boosting",
        "version": "v1.0",
        "artifact_id": "gradient_boosting_v1",
        "artifact_path": "models/classical/gradient_boosting_v1.joblib",
        "manifest_path": "models/classical/gradient_boosting_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 8,
        "classical_feature_count": 11,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v2.0",
        "score_semantics": "ensemble_vote_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "hist_gradient_boosting_v1": {
        "model_id": "hist_gradient_boosting_v1",
        "disease": "diabetes",
        "display_name": "Histogram Gradient Boosting",
        "family": "classical",
        "model_type": "hist_gradient_boosting",
        "version": "v1.0",
        "artifact_id": "hist_gradient_boosting_v1",
        "artifact_path": "models/classical/hist_gradient_boosting_v1.joblib",
        "manifest_path": "models/classical/hist_gradient_boosting_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 8,
        "classical_feature_count": 11,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v2.0",
        "score_semantics": "ensemble_vote_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "soft_voting_ensemble_v1": {
        "model_id": "soft_voting_ensemble_v1",
        "disease": "diabetes",
        "display_name": "Soft Voting Ensemble",
        "family": "classical",
        "model_type": "soft_voting",
        "version": "v1.0",
        "artifact_id": "soft_voting_ensemble_v1",
        "artifact_path": "models/classical/soft_voting_ensemble_v1.joblib",
        "manifest_path": "models/classical/soft_voting_ensemble_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 8,
        "classical_feature_count": 11,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v2.0",
        "score_semantics": "ensemble_vote_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "hard_voting_ensemble_v1": {
        "model_id": "hard_voting_ensemble_v1",
        "disease": "diabetes",
        "display_name": "Hard Voting Ensemble",
        "family": "classical",
        "model_type": "hard_voting",
        "version": "v1.0",
        "artifact_id": "hard_voting_ensemble_v1",
        "artifact_path": "models/classical/hard_voting_ensemble_v1.joblib",
        "manifest_path": "models/classical/hard_voting_ensemble_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 8,
        "classical_feature_count": 11,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v2.0",
        "score_semantics": "hard_voting_majority_class",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "stacking_ensemble_v1": {
        "model_id": "stacking_ensemble_v1",
        "disease": "diabetes",
        "display_name": "Stacking Ensemble",
        "family": "classical",
        "model_type": "stacking",
        "version": "v1.0",
        "artifact_id": "stacking_ensemble_v1",
        "artifact_path": "models/classical/stacking_ensemble_v1.joblib",
        "manifest_path": "models/classical/stacking_ensemble_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 8,
        "classical_feature_count": 11,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v2.0",
        "score_semantics": "ensemble_vote_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },

    # =========================================================================
    # CARDIOVASCULAR RISK (16 Models)
    # =========================================================================
    # Production Winner (Phase H Optimization)
    "cardiovascular_extra_trees_opt_v1": {
        "model_id": "cardiovascular_extra_trees_opt_v1",
        "disease": "cardiovascular",
        "display_name": "Cardiovascular Extra Trees (Optimized)",
        "family": "classical",
        "model_type": "extra_trees",
        "version": "v2.0_optimized",
        "artifact_id": "cardiovascular_extra_trees_opt_v1",
        "artifact_path": "models/cardiovascular/classical/cardiovascular_extra_trees_opt_v1.joblib",
        "manifest_path": "models/cardiovascular/classical/cardiovascular_extra_trees_opt_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": True,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 13,
        "classical_feature_count": 13,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "calibrated_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": "Optimized Extra Trees achieving highest PR-AUC (0.9300) and Recall (96.97%) on UCI Cleveland holdout partition.",
        "selection_metric": "PR-AUC=0.9300, Recall=96.97%",
    },
    "cardiovascular_rbf_svm_opt_v1": {
        "model_id": "cardiovascular_rbf_svm_opt_v1",
        "disease": "cardiovascular",
        "display_name": "Cardiovascular RBF SVM (Optimized)",
        "family": "classical",
        "model_type": "svm",
        "version": "v2.0_optimized",
        "artifact_id": "cardiovascular_rbf_svm_opt_v1",
        "artifact_path": "models/cardiovascular/classical/cardiovascular_rbf_svm_opt_v1.joblib",
        "manifest_path": "models/cardiovascular/classical/cardiovascular_rbf_svm_opt_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 13,
        "classical_feature_count": 13,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "calibrated_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cardiovascular_stacking_opt_v1": {
        "model_id": "cardiovascular_stacking_opt_v1",
        "disease": "cardiovascular",
        "display_name": "Cardiovascular Stacking Ensemble (Optimized)",
        "family": "classical",
        "model_type": "stacking",
        "version": "v2.0_optimized",
        "artifact_id": "cardiovascular_stacking_opt_v1",
        "artifact_path": "models/cardiovascular/classical/cardiovascular_stacking_opt_v1.joblib",
        "manifest_path": "models/cardiovascular/classical/cardiovascular_stacking_opt_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 13,
        "classical_feature_count": 13,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "ensemble_vote_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cardiovascular_logistic_regression_v1": {
        "model_id": "cardiovascular_logistic_regression_v1",
        "disease": "cardiovascular",
        "display_name": "Cardiovascular Logistic Regression",
        "family": "classical",
        "model_type": "logistic_regression",
        "version": "v1.0",
        "artifact_id": "cardiovascular_logistic_regression_v1",
        "artifact_path": "models/cardiovascular/classical/cardiovascular_logistic_regression_v1.joblib",
        "manifest_path": "models/cardiovascular/classical/cardiovascular_logistic_regression_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 13,
        "classical_feature_count": 13,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "calibrated_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cardiovascular_random_forest_v1": {
        "model_id": "cardiovascular_random_forest_v1",
        "disease": "cardiovascular",
        "display_name": "Cardiovascular Random Forest",
        "family": "classical",
        "model_type": "random_forest",
        "version": "v1.0",
        "artifact_id": "cardiovascular_random_forest_v1",
        "artifact_path": "models/cardiovascular/classical/cardiovascular_random_forest_v1.joblib",
        "manifest_path": "models/cardiovascular/classical/cardiovascular_random_forest_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 13,
        "classical_feature_count": 13,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "ensemble_vote_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cardiovascular_linear_svm_v1": {
        "model_id": "cardiovascular_linear_svm_v1",
        "disease": "cardiovascular",
        "display_name": "Cardiovascular Linear SVM",
        "family": "classical",
        "model_type": "linear_svm",
        "version": "v1.0",
        "artifact_id": "cardiovascular_linear_svm_v1",
        "artifact_path": "models/cardiovascular/classical/cardiovascular_linear_svm_v1.joblib",
        "manifest_path": "models/cardiovascular/classical/cardiovascular_linear_svm_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 13,
        "classical_feature_count": 13,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "calibrated_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cardiovascular_rbf_svm_v1": {
        "model_id": "cardiovascular_rbf_svm_v1",
        "disease": "cardiovascular",
        "display_name": "Cardiovascular RBF SVM",
        "family": "classical",
        "model_type": "svm",
        "version": "v1.0",
        "artifact_id": "cardiovascular_rbf_svm_v1",
        "artifact_path": "models/cardiovascular/classical/cardiovascular_rbf_svm_v1.joblib",
        "manifest_path": "models/cardiovascular/classical/cardiovascular_rbf_svm_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 13,
        "classical_feature_count": 13,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "calibrated_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cardiovascular_knn_v1": {
        "model_id": "cardiovascular_knn_v1",
        "disease": "cardiovascular",
        "display_name": "Cardiovascular KNN",
        "family": "classical",
        "model_type": "knn",
        "version": "v1.0",
        "artifact_id": "cardiovascular_knn_v1",
        "artifact_path": "models/cardiovascular/classical/cardiovascular_knn_v1.joblib",
        "manifest_path": "models/cardiovascular/classical/cardiovascular_knn_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 13,
        "classical_feature_count": 13,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "ensemble_vote_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cardiovascular_decision_tree_v1": {
        "model_id": "cardiovascular_decision_tree_v1",
        "disease": "cardiovascular",
        "display_name": "Cardiovascular Decision Tree",
        "family": "classical",
        "model_type": "decision_tree",
        "version": "v1.0",
        "artifact_id": "cardiovascular_decision_tree_v1",
        "artifact_path": "models/cardiovascular/classical/cardiovascular_decision_tree_v1.joblib",
        "manifest_path": "models/cardiovascular/classical/cardiovascular_decision_tree_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 13,
        "classical_feature_count": 13,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "ensemble_vote_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cardiovascular_extra_trees_v1": {
        "model_id": "cardiovascular_extra_trees_v1",
        "disease": "cardiovascular",
        "display_name": "Cardiovascular Extra Trees",
        "family": "classical",
        "model_type": "extra_trees",
        "version": "v1.0",
        "artifact_id": "cardiovascular_extra_trees_v1",
        "artifact_path": "models/cardiovascular/classical/cardiovascular_extra_trees_v1.joblib",
        "manifest_path": "models/cardiovascular/classical/cardiovascular_extra_trees_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 13,
        "classical_feature_count": 13,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "ensemble_vote_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cardiovascular_gradient_boosting_v1": {
        "model_id": "cardiovascular_gradient_boosting_v1",
        "disease": "cardiovascular",
        "display_name": "Cardiovascular Gradient Boosting",
        "family": "classical",
        "model_type": "gradient_boosting",
        "version": "v1.0",
        "artifact_id": "cardiovascular_gradient_boosting_v1",
        "artifact_path": "models/cardiovascular/classical/cardiovascular_gradient_boosting_v1.joblib",
        "manifest_path": "models/cardiovascular/classical/cardiovascular_gradient_boosting_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 13,
        "classical_feature_count": 13,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "ensemble_vote_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cardiovascular_hist_gradient_boosting_v1": {
        "model_id": "cardiovascular_hist_gradient_boosting_v1",
        "disease": "cardiovascular",
        "display_name": "Cardiovascular Hist Gradient Boosting",
        "family": "classical",
        "model_type": "hist_gradient_boosting",
        "version": "v1.0",
        "artifact_id": "cardiovascular_hist_gradient_boosting_v1",
        "artifact_path": "models/cardiovascular/classical/cardiovascular_hist_gradient_boosting_v1.joblib",
        "manifest_path": "models/cardiovascular/classical/cardiovascular_hist_gradient_boosting_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 13,
        "classical_feature_count": 13,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "ensemble_vote_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cardiovascular_xgboost_v1": {
        "model_id": "cardiovascular_xgboost_v1",
        "disease": "cardiovascular",
        "display_name": "Cardiovascular XGBoost",
        "family": "classical",
        "model_type": "xgboost",
        "version": "v1.0",
        "artifact_id": "cardiovascular_xgboost_v1",
        "artifact_path": "models/cardiovascular/classical/cardiovascular_xgboost_v1.joblib",
        "manifest_path": "models/cardiovascular/classical/cardiovascular_xgboost_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 13,
        "classical_feature_count": 13,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "ensemble_vote_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cardiovascular_soft_voting_ensemble_v1": {
        "model_id": "cardiovascular_soft_voting_ensemble_v1",
        "disease": "cardiovascular",
        "display_name": "Cardiovascular Soft Voting Ensemble",
        "family": "classical",
        "model_type": "soft_voting",
        "version": "v1.0",
        "artifact_id": "cardiovascular_soft_voting_ensemble_v1",
        "artifact_path": "models/cardiovascular/classical/cardiovascular_soft_voting_ensemble_v1.joblib",
        "manifest_path": "models/cardiovascular/classical/cardiovascular_soft_voting_ensemble_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 13,
        "classical_feature_count": 13,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "ensemble_vote_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cardiovascular_hard_voting_ensemble_v1": {
        "model_id": "cardiovascular_hard_voting_ensemble_v1",
        "disease": "cardiovascular",
        "display_name": "Cardiovascular Hard Voting Ensemble",
        "family": "classical",
        "model_type": "hard_voting",
        "version": "v1.0",
        "artifact_id": "cardiovascular_hard_voting_ensemble_v1",
        "artifact_path": "models/cardiovascular/classical/cardiovascular_hard_voting_ensemble_v1.joblib",
        "manifest_path": "models/cardiovascular/classical/cardiovascular_hard_voting_ensemble_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 13,
        "classical_feature_count": 13,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "hard_voting_majority_class",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cardiovascular_stacking_ensemble_v1": {
        "model_id": "cardiovascular_stacking_ensemble_v1",
        "disease": "cardiovascular",
        "display_name": "Cardiovascular Stacking Ensemble",
        "family": "classical",
        "model_type": "stacking",
        "version": "v1.0",
        "artifact_id": "cardiovascular_stacking_ensemble_v1",
        "artifact_path": "models/cardiovascular/classical/cardiovascular_stacking_ensemble_v1.joblib",
        "manifest_path": "models/cardiovascular/classical/cardiovascular_stacking_ensemble_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 13,
        "classical_feature_count": 13,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "ensemble_vote_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },

    "cardiovascular_qsvc_4q_v1": {
        "model_id": "cardiovascular_qsvc_4q_v1",
        "disease": "cardiovascular",
        "display_name": "Cardiovascular QSVC (4-Qubit)",
        "family": "quantum",
        "model_type": "qsvc",
        "version": "v1.0",
        "artifact_id": "cardiovascular_qsvc_4q_v1",
        "artifact_path": "models/cardiovascular/quantum/cardiovascular_qsvc_4q_v1.joblib",
        "manifest_path": "models/cardiovascular/quantum/cardiovascular_qsvc_4q_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": True,
        "quantum": True,
        "qubit_count": 4,
        "raw_feature_count": 13,
        "classical_feature_count": 13,
        "quantum_feature_count": 4,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "uncalibrated_quantum_decision_score",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cardiovascular_vqc_4q_v1": {
        "model_id": "cardiovascular_vqc_4q_v1",
        "disease": "cardiovascular",
        "display_name": "Cardiovascular VQC (4-Qubit)",
        "family": "quantum",
        "model_type": "vqc",
        "version": "v1.0",
        "artifact_id": "cardiovascular_vqc_4q_v1",
        "artifact_path": "models/cardiovascular/quantum/cardiovascular_vqc_4q_v1.joblib",
        "manifest_path": "models/cardiovascular/quantum/cardiovascular_vqc_4q_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": True,
        "quantum": True,
        "qubit_count": 4,
        "raw_feature_count": 13,
        "classical_feature_count": 13,
        "quantum_feature_count": 4,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "uncalibrated_quantum_decision_score",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cardiovascular_qsvc_6q_v1": {
        "model_id": "cardiovascular_qsvc_6q_v1",
        "disease": "cardiovascular",
        "display_name": "Cardiovascular QSVC (6-Qubit)",
        "family": "quantum",
        "model_type": "qsvc",
        "version": "v1.0",
        "artifact_id": "cardiovascular_qsvc_6q_v1",
        "artifact_path": "models/cardiovascular/quantum/cardiovascular_qsvc_6q_v1.joblib",
        "manifest_path": "models/cardiovascular/quantum/cardiovascular_qsvc_6q_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": True,
        "quantum": True,
        "qubit_count": 6,
        "raw_feature_count": 13,
        "classical_feature_count": 13,
        "quantum_feature_count": 6,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "uncalibrated_quantum_decision_score",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cardiovascular_vqc_6q_v1": {
        "model_id": "cardiovascular_vqc_6q_v1",
        "disease": "cardiovascular",
        "display_name": "Cardiovascular VQC (6-Qubit)",
        "family": "quantum",
        "model_type": "vqc",
        "version": "v1.0",
        "artifact_id": "cardiovascular_vqc_6q_v1",
        "artifact_path": "models/cardiovascular/quantum/cardiovascular_vqc_6q_v1.joblib",
        "manifest_path": "models/cardiovascular/quantum/cardiovascular_vqc_6q_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": True,
        "quantum": True,
        "qubit_count": 6,
        "raw_feature_count": 13,
        "classical_feature_count": 13,
        "quantum_feature_count": 6,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "uncalibrated_quantum_decision_score",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cardiovascular_qsvc_8q_v1": {
        "model_id": "cardiovascular_qsvc_8q_v1",
        "disease": "cardiovascular",
        "display_name": "Cardiovascular QSVC (8-Qubit)",
        "family": "quantum",
        "model_type": "qsvc",
        "version": "v1.0",
        "artifact_id": "cardiovascular_qsvc_8q_v1",
        "artifact_path": "models/cardiovascular/quantum/cardiovascular_qsvc_8q_v1.joblib",
        "manifest_path": "models/cardiovascular/quantum/cardiovascular_qsvc_8q_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": True,
        "quantum": True,
        "qubit_count": 8,
        "raw_feature_count": 13,
        "classical_feature_count": 13,
        "quantum_feature_count": 8,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "uncalibrated_quantum_decision_score",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cardiovascular_vqc_8q_v1": {
        "model_id": "cardiovascular_vqc_8q_v1",
        "disease": "cardiovascular",
        "display_name": "Cardiovascular VQC (8-Qubit)",
        "family": "quantum",
        "model_type": "vqc",
        "version": "v1.0",
        "artifact_id": "cardiovascular_vqc_8q_v1",
        "artifact_path": "models/cardiovascular/quantum/cardiovascular_vqc_8q_v1.joblib",
        "manifest_path": "models/cardiovascular/quantum/cardiovascular_vqc_8q_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": True,
        "quantum": True,
        "qubit_count": 8,
        "raw_feature_count": 13,
        "classical_feature_count": 13,
        "quantum_feature_count": 8,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "uncalibrated_quantum_decision_score",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },

    # =========================================================================
    # BREAST CANCER ONCOLOGY (22 Models)
    # =========================================================================
    # Production Winner (Phase H Optimization)
    "cancer_stacking_opt_v1": {
        "model_id": "cancer_stacking_opt_v1",
        "disease": "cancer",
        "display_name": "Breast Cancer Stacking Ensemble (Optimized)",
        "family": "classical",
        "model_type": "stacking",
        "version": "v2.0_optimized",
        "artifact_id": "cancer_stacking_opt_v1",
        "artifact_path": "models/cancer/classical/cancer_stacking_opt_v1.joblib",
        "manifest_path": "models/cancer/classical/cancer_stacking_opt_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": True,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 30,
        "classical_feature_count": 30,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "ensemble_vote_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": "Optimized Stacking Ensemble maximizing F1 score (0.9880) and Accuracy (99.12%) on Wisconsin Diagnostic holdout partition.",
        "selection_metric": "PR-AUC=0.9951, F1=0.9880",
    },
    "cancer_rf_opt_v1": {
        "model_id": "cancer_rf_opt_v1",
        "disease": "cancer",
        "display_name": "Breast Cancer Random Forest (Optimized)",
        "family": "classical",
        "model_type": "random_forest",
        "version": "v2.0_optimized",
        "artifact_id": "cancer_rf_opt_v1",
        "artifact_path": "models/cancer/classical/cancer_rf_opt_v1.joblib",
        "manifest_path": "models/cancer/classical/cancer_rf_opt_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 30,
        "classical_feature_count": 30,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "calibrated_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cancer_soft_voting_opt_v1": {
        "model_id": "cancer_soft_voting_opt_v1",
        "disease": "cancer",
        "display_name": "Breast Cancer Soft Voting Ensemble (Optimized)",
        "family": "classical",
        "model_type": "soft_voting",
        "version": "v2.0_optimized",
        "artifact_id": "cancer_soft_voting_opt_v1",
        "artifact_path": "models/cancer/classical/cancer_soft_voting_opt_v1.joblib",
        "manifest_path": "models/cancer/classical/cancer_soft_voting_opt_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 30,
        "classical_feature_count": 30,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "ensemble_vote_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cancer_logistic_regression_v1": {
        "model_id": "cancer_logistic_regression_v1",
        "disease": "cancer",
        "display_name": "Breast Cancer Logistic Regression",
        "family": "classical",
        "model_type": "logistic_regression",
        "version": "v1.0",
        "artifact_id": "cancer_logistic_regression_v1",
        "artifact_path": "models/cancer/classical/cancer_logistic_regression_v1.joblib",
        "manifest_path": "models/cancer/classical/cancer_logistic_regression_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 30,
        "classical_feature_count": 30,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "calibrated_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cancer_random_forest_v1": {
        "model_id": "cancer_random_forest_v1",
        "disease": "cancer",
        "display_name": "Breast Cancer Random Forest",
        "family": "classical",
        "model_type": "random_forest",
        "version": "v1.0",
        "artifact_id": "cancer_random_forest_v1",
        "artifact_path": "models/cancer/classical/cancer_random_forest_v1.joblib",
        "manifest_path": "models/cancer/classical/cancer_random_forest_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 30,
        "classical_feature_count": 30,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "ensemble_vote_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cancer_linear_svm_v1": {
        "model_id": "cancer_linear_svm_v1",
        "disease": "cancer",
        "display_name": "Breast Cancer Linear SVM",
        "family": "classical",
        "model_type": "linear_svm",
        "version": "v1.0",
        "artifact_id": "cancer_linear_svm_v1",
        "artifact_path": "models/cancer/classical/cancer_linear_svm_v1.joblib",
        "manifest_path": "models/cancer/classical/cancer_linear_svm_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 30,
        "classical_feature_count": 30,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "calibrated_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cancer_rbf_svm_v1": {
        "model_id": "cancer_rbf_svm_v1",
        "disease": "cancer",
        "display_name": "Breast Cancer RBF SVM",
        "family": "classical",
        "model_type": "svm",
        "version": "v1.0",
        "artifact_id": "cancer_rbf_svm_v1",
        "artifact_path": "models/cancer/classical/cancer_rbf_svm_v1.joblib",
        "manifest_path": "models/cancer/classical/cancer_rbf_svm_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 30,
        "classical_feature_count": 30,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "calibrated_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cancer_knn_v1": {
        "model_id": "cancer_knn_v1",
        "disease": "cancer",
        "display_name": "Breast Cancer KNN",
        "family": "classical",
        "model_type": "knn",
        "version": "v1.0",
        "artifact_id": "cancer_knn_v1",
        "artifact_path": "models/cancer/classical/cancer_knn_v1.joblib",
        "manifest_path": "models/cancer/classical/cancer_knn_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 30,
        "classical_feature_count": 30,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "ensemble_vote_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cancer_decision_tree_v1": {
        "model_id": "cancer_decision_tree_v1",
        "disease": "cancer",
        "display_name": "Breast Cancer Decision Tree",
        "family": "classical",
        "model_type": "decision_tree",
        "version": "v1.0",
        "artifact_id": "cancer_decision_tree_v1",
        "artifact_path": "models/cancer/classical/cancer_decision_tree_v1.joblib",
        "manifest_path": "models/cancer/classical/cancer_decision_tree_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 30,
        "classical_feature_count": 30,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "ensemble_vote_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cancer_extra_trees_v1": {
        "model_id": "cancer_extra_trees_v1",
        "disease": "cancer",
        "display_name": "Breast Cancer Extra Trees",
        "family": "classical",
        "model_type": "extra_trees",
        "version": "v1.0",
        "artifact_id": "cancer_extra_trees_v1",
        "artifact_path": "models/cancer/classical/cancer_extra_trees_v1.joblib",
        "manifest_path": "models/cancer/classical/cancer_extra_trees_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 30,
        "classical_feature_count": 30,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "ensemble_vote_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cancer_gradient_boosting_v1": {
        "model_id": "cancer_gradient_boosting_v1",
        "disease": "cancer",
        "display_name": "Breast Cancer Gradient Boosting",
        "family": "classical",
        "model_type": "gradient_boosting",
        "version": "v1.0",
        "artifact_id": "cancer_gradient_boosting_v1",
        "artifact_path": "models/cancer/classical/cancer_gradient_boosting_v1.joblib",
        "manifest_path": "models/cancer/classical/cancer_gradient_boosting_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 30,
        "classical_feature_count": 30,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "ensemble_vote_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cancer_hist_gradient_boosting_v1": {
        "model_id": "cancer_hist_gradient_boosting_v1",
        "disease": "cancer",
        "display_name": "Breast Cancer Hist Gradient Boosting",
        "family": "classical",
        "model_type": "hist_gradient_boosting",
        "version": "v1.0",
        "artifact_id": "cancer_hist_gradient_boosting_v1",
        "artifact_path": "models/cancer/classical/cancer_hist_gradient_boosting_v1.joblib",
        "manifest_path": "models/cancer/classical/cancer_hist_gradient_boosting_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 30,
        "classical_feature_count": 30,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "ensemble_vote_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cancer_xgboost_v1": {
        "model_id": "cancer_xgboost_v1",
        "disease": "cancer",
        "display_name": "Breast Cancer XGBoost",
        "family": "classical",
        "model_type": "xgboost",
        "version": "v1.0",
        "artifact_id": "cancer_xgboost_v1",
        "artifact_path": "models/cancer/classical/cancer_xgboost_v1.joblib",
        "manifest_path": "models/cancer/classical/cancer_xgboost_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 30,
        "classical_feature_count": 30,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "ensemble_vote_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cancer_soft_voting_ensemble_v1": {
        "model_id": "cancer_soft_voting_ensemble_v1",
        "disease": "cancer",
        "display_name": "Breast Cancer Soft Voting Ensemble",
        "family": "classical",
        "model_type": "soft_voting",
        "version": "v1.0",
        "artifact_id": "cancer_soft_voting_ensemble_v1",
        "artifact_path": "models/cancer/classical/cancer_soft_voting_ensemble_v1.joblib",
        "manifest_path": "models/cancer/classical/cancer_soft_voting_ensemble_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 30,
        "classical_feature_count": 30,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "ensemble_vote_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cancer_hard_voting_ensemble_v1": {
        "model_id": "cancer_hard_voting_ensemble_v1",
        "disease": "cancer",
        "display_name": "Breast Cancer Hard Voting Ensemble",
        "family": "classical",
        "model_type": "hard_voting",
        "version": "v1.0",
        "artifact_id": "cancer_hard_voting_ensemble_v1",
        "artifact_path": "models/cancer/classical/cancer_hard_voting_ensemble_v1.joblib",
        "manifest_path": "models/cancer/classical/cancer_hard_voting_ensemble_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 30,
        "classical_feature_count": 30,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "hard_voting_majority_class",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cancer_stacking_ensemble_v1": {
        "model_id": "cancer_stacking_ensemble_v1",
        "disease": "cancer",
        "display_name": "Breast Cancer Stacking Ensemble",
        "family": "classical",
        "model_type": "stacking",
        "version": "v1.0",
        "artifact_id": "cancer_stacking_ensemble_v1",
        "artifact_path": "models/cancer/classical/cancer_stacking_ensemble_v1.joblib",
        "manifest_path": "models/cancer/classical/cancer_stacking_ensemble_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": False,
        "quantum": False,
        "qubit_count": None,
        "raw_feature_count": 30,
        "classical_feature_count": 30,
        "quantum_feature_count": None,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "ensemble_vote_probability",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cancer_qsvc_4q_v1": {
        "model_id": "cancer_qsvc_4q_v1",
        "disease": "cancer",
        "display_name": "Breast Cancer QSVC (4-Qubit)",
        "family": "quantum",
        "model_type": "qsvc",
        "version": "v1.0",
        "artifact_id": "cancer_qsvc_4q_v1",
        "artifact_path": "models/cancer/quantum/cancer_qsvc_4q_v1.joblib",
        "manifest_path": "models/cancer/quantum/cancer_qsvc_4q_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": True,
        "quantum": True,
        "qubit_count": 4,
        "raw_feature_count": 30,
        "classical_feature_count": 30,
        "quantum_feature_count": 4,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "uncalibrated_quantum_decision_score",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cancer_vqc_4q_v1": {
        "model_id": "cancer_vqc_4q_v1",
        "disease": "cancer",
        "display_name": "Breast Cancer VQC (4-Qubit)",
        "family": "quantum",
        "model_type": "vqc",
        "version": "v1.0",
        "artifact_id": "cancer_vqc_4q_v1",
        "artifact_path": "models/cancer/quantum/cancer_vqc_4q_v1.joblib",
        "manifest_path": "models/cancer/quantum/cancer_vqc_4q_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": True,
        "quantum": True,
        "qubit_count": 4,
        "raw_feature_count": 30,
        "classical_feature_count": 30,
        "quantum_feature_count": 4,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "uncalibrated_quantum_decision_score",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cancer_qsvc_6q_v1": {
        "model_id": "cancer_qsvc_6q_v1",
        "disease": "cancer",
        "display_name": "Breast Cancer QSVC (6-Qubit)",
        "family": "quantum",
        "model_type": "qsvc",
        "version": "v1.0",
        "artifact_id": "cancer_qsvc_6q_v1",
        "artifact_path": "models/cancer/quantum/cancer_qsvc_6q_v1.joblib",
        "manifest_path": "models/cancer/quantum/cancer_qsvc_6q_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": True,
        "quantum": True,
        "qubit_count": 6,
        "raw_feature_count": 30,
        "classical_feature_count": 30,
        "quantum_feature_count": 6,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "uncalibrated_quantum_decision_score",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cancer_vqc_6q_v1": {
        "model_id": "cancer_vqc_6q_v1",
        "disease": "cancer",
        "display_name": "Breast Cancer VQC (6-Qubit)",
        "family": "quantum",
        "model_type": "vqc",
        "version": "v1.0",
        "artifact_id": "cancer_vqc_6q_v1",
        "artifact_path": "models/cancer/quantum/cancer_vqc_6q_v1.joblib",
        "manifest_path": "models/cancer/quantum/cancer_vqc_6q_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": True,
        "quantum": True,
        "qubit_count": 6,
        "raw_feature_count": 30,
        "classical_feature_count": 30,
        "quantum_feature_count": 6,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "uncalibrated_quantum_decision_score",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cancer_qsvc_8q_v1": {
        "model_id": "cancer_qsvc_8q_v1",
        "disease": "cancer",
        "display_name": "Breast Cancer QSVC (8-Qubit)",
        "family": "quantum",
        "model_type": "qsvc",
        "version": "v1.0",
        "artifact_id": "cancer_qsvc_8q_v1",
        "artifact_path": "models/cancer/quantum/cancer_qsvc_8q_v1.joblib",
        "manifest_path": "models/cancer/quantum/cancer_qsvc_8q_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": True,
        "quantum": True,
        "qubit_count": 8,
        "raw_feature_count": 30,
        "classical_feature_count": 30,
        "quantum_feature_count": 8,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "uncalibrated_quantum_decision_score",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
    "cancer_vqc_8q_v1": {
        "model_id": "cancer_vqc_8q_v1",
        "disease": "cancer",
        "display_name": "Breast Cancer VQC (8-Qubit)",
        "family": "quantum",
        "model_type": "vqc",
        "version": "v1.0",
        "artifact_id": "cancer_vqc_8q_v1",
        "artifact_path": "models/cancer/quantum/cancer_vqc_8q_v1.joblib",
        "manifest_path": "models/cancer/quantum/cancer_vqc_8q_v1_manifest.json",
        "status": "Ready",
        "trained": True,
        "evaluated": True,
        "production": False,
        "experimental": True,
        "quantum": True,
        "qubit_count": 8,
        "raw_feature_count": 30,
        "classical_feature_count": 30,
        "quantum_feature_count": 8,
        "dataset_version": "v1.0",
        "pipeline_version": "v1.0",
        "score_semantics": "uncalibrated_quantum_decision_score",
        "explainability_support": True,
        "evaluation_support": True,
        "selection_reason": None,
        "selection_metric": None,
    },
}

# Controlled Aliases Mapping to Canonical Model IDs
MODEL_ALIASES: dict[str, str] = {
    # Phase B & C backward compatibility aliases
    "logistic_regression_v2": "logistic_regression_v3",
    "svm_v2": "svm_v3",
    "random_forest_v2": "random_forest_v3",
    "xgboost_v2": "xgboost_v3",
    "qsvc_v2": "qsvc_v3",
    "vqc_v2": "vqc_v3",

    # Generic Aliases (Diabetes context)
    "logistic_regression": "logistic_regression_v3",
    "logistic": "logistic_regression_v3",
    "lr": "logistic_regression_v3",
    "svm": "svm_v3",
    "svc": "svm_v3",
    "random_forest": "random_forest_v3",
    "rf": "random_forest_v3",
    "xgboost": "xgboost_v3",
    "xgb": "xgboost_v3",
    "qsvc": "qsvc_v3",
    "qsvc-4q": "qsvc_v3",
    "vqc": "vqc_v3",
    "vqc-4q": "vqc_v3",
    "qsvc_6q": "qsvc_6q_v1",
    "qsvc-6q": "qsvc_6q_v1",
    "vqc_6q": "vqc_6q_v1",
    "vqc-6q": "vqc_6q_v1",
    "qsvc_8q": "qsvc_8q_v1",
    "qsvc-8q": "qsvc_8q_v1",
    "vqc_8q": "vqc_8q_v1",
    "vqc-8q": "vqc_8q_v1",
    "diabetes_default": "diabetes_rf_opt_v1",
    "diabetes_production": "diabetes_rf_opt_v1",
    "diabetes_optimized": "diabetes_rf_opt_v1",
    "diabetes_voting": "diabetes_soft_voting_opt_v1",


    # Cardiovascular Aliases
    "cardio_default": "cardiovascular_extra_trees_opt_v1",
    "cardio_production": "cardiovascular_extra_trees_opt_v1",
    "cardio_opt": "cardiovascular_extra_trees_opt_v1",
    "cardiovascular_optimized": "cardiovascular_extra_trees_opt_v1",
    "cardio_rf": "cardiovascular_random_forest_v1",
    "cardio_lr": "cardiovascular_logistic_regression_v1",
    "cardio_svm": "cardiovascular_rbf_svm_v1",
    "cardio_xgb": "cardiovascular_xgboost_v1",
    "cardio_et": "cardiovascular_extra_trees_v1",
    "cardio_gb": "cardiovascular_gradient_boosting_v1",
    "cardio_knn": "cardiovascular_knn_v1",
    "cardio_dt": "cardiovascular_decision_tree_v1",
    "cardio_qsvc": "cardiovascular_qsvc_4q_v1",
    "cardio_qsvc_4q": "cardiovascular_qsvc_4q_v1",
    "cardio_qsvc-4q": "cardiovascular_qsvc_4q_v1",
    "cardio_vqc": "cardiovascular_vqc_4q_v1",
    "cardio_vqc_4q": "cardiovascular_vqc_4q_v1",
    "cardio_vqc-4q": "cardiovascular_vqc_4q_v1",
    "cardio_qsvc_6q": "cardiovascular_qsvc_6q_v1",
    "cardio_qsvc-6q": "cardiovascular_qsvc_6q_v1",
    "cardio_vqc_6q": "cardiovascular_vqc_6q_v1",
    "cardio_vqc-6q": "cardiovascular_vqc_6q_v1",
    "cardio_qsvc_8q": "cardiovascular_qsvc_8q_v1",
    "cardio_qsvc-8q": "cardiovascular_qsvc_8q_v1",
    "cardio_vqc_8q": "cardiovascular_vqc_8q_v1",
    "cardio_vqc-8q": "cardiovascular_vqc_8q_v1",
    "cardiovascular_qsvc": "cardiovascular_qsvc_4q_v1",
    "cardiovascular_vqc": "cardiovascular_vqc_4q_v1",

    # Cancer Aliases
    "cancer_default": "cancer_stacking_opt_v1",
    "cancer_production": "cancer_stacking_opt_v1",
    "cancer_opt": "cancer_stacking_opt_v1",
    "cancer_optimized": "cancer_stacking_opt_v1",
    "cancer_rf": "cancer_random_forest_v1",
    "cancer_lr": "cancer_logistic_regression_v1",
    "cancer_svm": "cancer_rbf_svm_v1",
    "cancer_xgb": "cancer_xgboost_v1",
    "cancer_et": "cancer_extra_trees_v1",
    "cancer_gb": "cancer_gradient_boosting_v1",
    "cancer_knn": "cancer_knn_v1",
    "cancer_dt": "cancer_decision_tree_v1",
    "cancer_qsvc": "cancer_qsvc_4q_v1",
    "cancer_qsvc_4q": "cancer_qsvc_4q_v1",
    "cancer_qsvc-4q": "cancer_qsvc_4q_v1",
    "cancer_vqc": "cancer_vqc_4q_v1",
    "cancer_vqc_4q": "cancer_vqc_4q_v1",
    "cancer_vqc-4q": "cancer_vqc_4q_v1",
    "cancer_qsvc_6q": "cancer_qsvc_6q_v1",
    "cancer_qsvc-6q": "cancer_qsvc_6q_v1",
    "cancer_vqc_6q": "cancer_vqc_6q_v1",
    "cancer_vqc-6q": "cancer_vqc_6q_v1",
    "cancer_qsvc_8q": "cancer_qsvc_8q_v1",
    "cancer_qsvc-8q": "cancer_qsvc_8q_v1",
    "cancer_vqc_8q": "cancer_vqc_8q_v1",
    "cancer_vqc-8q": "cancer_vqc_8q_v1",
}

# Unified Complete Registry
MODEL_REGISTRY: dict[str, dict[str, Any]] = {}
for mid, mdef in CANONICAL_MODELS.items():
    MODEL_REGISTRY[mid.lower()] = {
        "artifact_id": mdef["artifact_id"],
        "disease": mdef["disease"],
        "family": mdef["family"],
        "name": mdef["display_name"],
        "is_canonical": True,
    }

for alias_key, target_id in MODEL_ALIASES.items():
    target_def = CANONICAL_MODELS[target_id]
    MODEL_REGISTRY[alias_key.lower()] = {
        "artifact_id": target_def["artifact_id"],
        "disease": target_def["disease"],
        "family": target_def["family"],
        "name": target_def["display_name"],
        "is_canonical": False,
    }

FEATURE_COLUMNS = list(RAW_FEATURE_NAMES)


class MLService:
    """Production ML Inference Service managing authoritative model artifact resolution, caching, and prediction execution."""

    def __init__(self, models_dir: str | Path = "models"):
        self.models_dir = Path(models_dir)
        self._cache: dict[str, ModelArtifact] = {}

    def resolve_artifact_id(
        self,
        model_identifier: str,
        disease: str | None = None,
    ) -> str:
        """Resolves user model key or alias to trusted artifact ID with strict disease boundary validation.

        Security & Integrity Rules:
        - Rejects path traversal sequences (.., /, \\).
        - Rejects unknown model keys with HTTP 404.
        - Enforces disease boundary: if disease is provided, rejects models registered to other diseases.
        """
        raw_id = model_identifier.strip()
        key = raw_id.lower()

        # Security check for malicious path sequences
        if ".." in raw_id or "/" in raw_id or "\\" in raw_id:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Model '{model_identifier}' not found in registry (invalid identifier).",
            )

        target_disease = disease.lower().strip() if disease else None

        # Contextual generic alias resolution based on disease
        if target_disease:
            generic_disease_map = {
                "cardiovascular": {
                    "default": "cardiovascular_extra_trees_opt_v1",
                    "production": "cardiovascular_extra_trees_opt_v1",
                    "optimized": "cardiovascular_extra_trees_opt_v1",
                    "rf": "cardiovascular_random_forest_v1",
                    "random_forest": "cardiovascular_random_forest_v1",
                    "lr": "cardiovascular_logistic_regression_v1",
                    "logistic_regression": "cardiovascular_logistic_regression_v1",
                    "logistic": "cardiovascular_logistic_regression_v1",
                    "svm": "cardiovascular_rbf_svm_v1",
                    "rbf_svm": "cardiovascular_rbf_svm_v1",
                    "linear_svm": "cardiovascular_linear_svm_v1",
                    "xgb": "cardiovascular_xgboost_v1",
                    "xgboost": "cardiovascular_xgboost_v1",
                    "knn": "cardiovascular_knn_v1",
                    "decision_tree": "cardiovascular_decision_tree_v1",
                    "extra_trees": "cardiovascular_extra_trees_v1",
                    "gradient_boosting": "cardiovascular_gradient_boosting_v1",
                    "hist_gradient_boosting": "cardiovascular_hist_gradient_boosting_v1",
                    "soft_voting": "cardiovascular_soft_voting_ensemble_v1",
                    "hard_voting": "cardiovascular_hard_voting_ensemble_v1",
                    "stacking": "cardiovascular_stacking_ensemble_v1",
                    "qsvc": "cardiovascular_qsvc_4q_v1",
                    "vqc": "cardiovascular_vqc_4q_v1",
                    "qsvc_4q": "cardiovascular_qsvc_4q_v1",
                    "vqc_4q": "cardiovascular_vqc_4q_v1",
                    "qsvc_6q": "cardiovascular_qsvc_6q_v1",
                    "vqc_6q": "cardiovascular_vqc_6q_v1",
                    "qsvc_8q": "cardiovascular_qsvc_8q_v1",
                    "vqc_8q": "cardiovascular_vqc_8q_v1",
                },
                "cancer": {
                    "default": "cancer_stacking_opt_v1",
                    "production": "cancer_stacking_opt_v1",
                    "optimized": "cancer_stacking_opt_v1",
                    "rf": "cancer_random_forest_v1",
                    "random_forest": "cancer_random_forest_v1",
                    "lr": "cancer_logistic_regression_v1",
                    "logistic_regression": "cancer_logistic_regression_v1",
                    "logistic": "cancer_logistic_regression_v1",
                    "svm": "cancer_rbf_svm_v1",
                    "rbf_svm": "cancer_rbf_svm_v1",
                    "linear_svm": "cancer_linear_svm_v1",
                    "xgb": "cancer_xgboost_v1",
                    "xgboost": "cancer_xgboost_v1",
                    "knn": "cancer_knn_v1",
                    "decision_tree": "cancer_decision_tree_v1",
                    "extra_trees": "cancer_extra_trees_v1",
                    "gradient_boosting": "cancer_gradient_boosting_v1",
                    "hist_gradient_boosting": "cancer_hist_gradient_boosting_v1",
                    "soft_voting": "cancer_soft_voting_ensemble_v1",
                    "hard_voting": "cancer_hard_voting_ensemble_v1",
                    "stacking": "cancer_stacking_ensemble_v1",
                    "qsvc": "cancer_qsvc_4q_v1",
                    "vqc": "cancer_vqc_4q_v1",
                    "qsvc_4q": "cancer_qsvc_4q_v1",
                    "vqc_4q": "cancer_vqc_4q_v1",
                    "qsvc_6q": "cancer_qsvc_6q_v1",
                    "vqc_6q": "cancer_vqc_6q_v1",
                    "qsvc_8q": "cancer_qsvc_8q_v1",
                    "vqc_8q": "cancer_vqc_8q_v1",
                },
                "diabetes": {
                    "default": "diabetes_rf_opt_v1",
                    "production": "diabetes_rf_opt_v1",
                    "optimized": "diabetes_rf_opt_v1",
                    "qsvc": "qsvc_v3",
                    "vqc": "vqc_v3",
                    "qsvc_4q": "qsvc_v3",
                    "vqc_4q": "vqc_v3",
                    "qsvc_6q": "qsvc_6q_v1",
                    "vqc_6q": "vqc_6q_v1",
                    "qsvc_8q": "qsvc_8q_v1",
                    "vqc_8q": "vqc_8q_v1",
                },
            }
            if target_disease in generic_disease_map and key in generic_disease_map[target_disease]:
                key = generic_disease_map[target_disease][key]

        if key not in MODEL_REGISTRY:
            supported = sorted(list(CANONICAL_MODELS.keys()))
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Model '{model_identifier}' not found in registry. Supported models: {supported}",
            )

        entry = MODEL_REGISTRY[key]
        entry_disease = entry["disease"]

        # Hard Disease Boundary Validation: Reject cross-disease model execution
        if target_disease and entry_disease != target_disease:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail=(
                    f"Cross-disease execution violation: Model '{model_identifier}' belongs to disease domain '{entry_disease}', "
                    f"which does not match requested disease '{target_disease}'."
                ),
            )

        return entry["artifact_id"]

    def get_artifact(self, artifact_id: str) -> ModelArtifact:
        """Retrieves cached ModelArtifact or loads from disk safely."""
        if artifact_id not in self._cache:
            try:
                artifact = load_artifact(artifact_id, base_dir=self.models_dir)
                self._cache[artifact_id] = artifact
                logger.info(f"Loaded and cached ModelArtifact '{artifact_id}' ({artifact.model_name})")
            except ModelError as e:
                logger.error(f"Failed to load artifact '{artifact_id}': {e!s}")
                raise HTTPException(
                    status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                    detail=f"Model artifact '{artifact_id}' is unavailable or failed to initialize.",
                )
            except ValidationError as e:
                logger.error(f"Security validation failed for artifact '{artifact_id}': {e!s}")
                raise HTTPException(
                    status_code=status.HTTP_400_BAD_REQUEST,
                    detail=f"Invalid artifact request: {e!s}",
                )
        return self._cache[artifact_id]

    def format_input_dataframe(
        self,
        features: dict[str, float] | list[float],
        expected_columns: list[str] | None = None,
    ) -> pd.DataFrame:
        """Converts heterogeneous feature input into validated 1-row DataFrame."""
        target_cols = expected_columns if expected_columns is not None else FEATURE_COLUMNS
        if isinstance(features, dict):
            for t in ["Outcome", "outcome", "target", "Malignant", "malignant"]:
                if t in features:
                    raise HTTPException(
                        status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                        detail=f"Target column '{t}' must not be provided as an input feature.",
                    )
            missing = [col for col in target_cols if col not in features]
            if missing:
                raise HTTPException(
                    status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                    detail=f"Missing required biomedical features: {missing}",
                )
            extra_keys = [k for k in features if k not in target_cols]
            if extra_keys:
                raise HTTPException(
                    status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                    detail=f"Input contains unauthorized extra feature keys: {extra_keys}. Only raw predictor features are allowed.",
                )
            df = pd.DataFrame([{col: float(features[col]) for col in target_cols}])
        elif isinstance(features, list):
            if len(features) != len(target_cols):
                raise HTTPException(
                    status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                    detail=f"Feature list must contain exactly {len(target_cols)} values (got {len(features)}).",
                )
            df = pd.DataFrame([features], columns=target_cols)
        else:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail="Unsupported feature input format.",
            )

        # Validate numeric non-empty finite values
        arr = df.to_numpy(dtype=float)
        if np.isnan(arr).any() or np.isinf(arr).any():
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail="Input features contain NaN or infinite values.",
            )
        return df

    def predict(self, request: InferenceRequest) -> InferenceResponse:
        """Executes full inference lifecycle with strict disease boundary validation and explainability."""
        start_time = time.perf_counter()

        target_disease = request.disease.lower().strip() if request.disease else "diabetes"

        # 1. Resolve & load artifact with disease context
        art_id = self.resolve_artifact_id(request.model_id, disease=target_disease)
        artifact = self.get_artifact(art_id)

        canonical_def = CANONICAL_MODELS.get(art_id, {})

        # 2. Determine expected features from artifact preprocessor
        exp_cols = None
        if hasattr(artifact, "preprocessor"):
            if hasattr(artifact.preprocessor, "get_raw_feature_names"):
                exp_cols = artifact.preprocessor.get_raw_feature_names()
            elif hasattr(artifact.preprocessor, "get_feature_names"):
                exp_cols = artifact.preprocessor.get_feature_names()

        # 3. Format features (validation first)
        df_input = self.format_input_dataframe(request.features, expected_columns=exp_cols)

        # 4. Predict & compute probability
        try:
            preds = artifact.predict(df_input)
            pred_val = int(np.asarray(preds).ravel()[0])

            prob_val: float | None = None
            conf_val: float | None = None

            try:
                probs = artifact.predict_proba(df_input)
                probs_arr = np.asarray(probs)
                if probs_arr.ndim == 2 and probs_arr.shape[1] >= 2:
                    p0 = float(probs_arr[0, 0])
                    p1 = float(probs_arr[0, 1])
                    prob_val = p1
                    conf_val = max(p0, p1)
                elif probs_arr.ndim == 1:
                    p1 = float(probs_arr[0])
                    p0 = 1.0 - p1
                    prob_val = p1
                    conf_val = max(p0, p1)
            except Exception as e:
                logger.debug(f"Probability estimation not available for model '{art_id}': {e!s}")

            # Apply frozen decision threshold if configured in artifact metadata
            frozen_thresh = getattr(artifact, "configuration_provenance", {}).get("frozen_threshold")
            if frozen_thresh is not None and prob_val is not None:
                pred_val = 1 if prob_val >= float(frozen_thresh) else 0

            # 5. Optional Explainability
            explanation_payload: ExplanationResult | None = None
            if request.explain:
                expl_res = explanation_service.explain(artifact, df_input, top_k=8)
                feature_items = [
                    ExplanationContribution(
                        name=f.name,
                        value=f.value,
                        contribution=f.contribution,
                        direction=f.direction,
                        normalized_weight=f.normalized_weight,
                    )
                    for f in expl_res.features
                ]
                explanation_payload = ExplanationResult(
                    model_name=expl_res.model_name,
                    model_version=expl_res.model_family,
                    explanation_method=expl_res.method,
                    predicted_class=pred_val,
                    contributions=feature_items,
                    inference_context=request.evaluation_context,
                    status=expl_res.status,
                    limitations=expl_res.limitations,
                )

            # Score semantics derivation
            score_semantics = canonical_def.get("score_semantics")
            if not score_semantics:
                m_type = getattr(artifact, "model_type", "").lower()
                m_fam = getattr(artifact, "model_family", "").lower()
                if m_fam == "quantum" or m_type in ["qsvc", "vqc"]:
                    score_semantics = "uncalibrated_quantum_decision_score"
                elif m_type in ["hard_voting", "hard_voting_ensemble"]:
                    score_semantics = "hard_voting_majority_class"
                elif m_type in ["soft_voting", "stacking"]:
                    score_semantics = "ensemble_vote_probability"
                else:
                    score_semantics = "calibrated_probability"

            latency_ms = round((time.perf_counter() - start_time) * 1000.0, 2)

            import uuid
            from datetime import datetime

            inf_id = f"inf_{uuid.uuid4().hex[:12]}"

            return InferenceResponse(
                inference_id=inf_id,
                disease=target_disease,
                predicted_class=pred_val,
                probability=round(prob_val, 4) if prob_val is not None else None,
                decision_score=round(conf_val, 4) if conf_val is not None else None,
                score_semantics=score_semantics,
                model_output="High Risk" if pred_val == 1 else "Low Risk",
                model_used=artifact.model_name,
                model_family=artifact.model_family,
                artifact_id=artifact.artifact_id,
                artifact_version=getattr(artifact, "artifact_version", canonical_def.get("version", "v1.0")),
                pipeline_version=getattr(artifact.preprocessor, "pipeline_version", canonical_def.get("pipeline_version", "v1.0")),
                explanation=explanation_payload,
                audit=AuditMetadata(
                    timestamp=datetime.now().isoformat(),
                    request_id=inf_id,
                    inference_time_ms=latency_ms,
                ),
            )

        except HTTPException:
            raise
        except Exception as e:
            logger.error(f"Inference error with model '{art_id}': {e!s}", exc_info=True)
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail=f"Inference execution failed: {e!s}",
            )

    def get_registered_models_summary(
        self, disease: str | None = None
    ) -> list[dict[str, Any]]:
        """Returns metadata for all authoritative canonical models filtered by disease."""
        target_disease = disease.lower().strip() if disease and disease.lower() != "all" else None
        models_info = []

        for mid, mdef in CANONICAL_MODELS.items():
            if target_disease and mdef["disease"] != target_disease:
                continue

            models_info.append({
                "model_id": mdef["model_id"],
                "disease": mdef["disease"],
                "display_name": mdef["display_name"],
                "name": mdef["display_name"],
                "family": mdef["family"],
                "model_family": mdef["family"],
                "model_type": mdef["model_type"],
                "version": mdef["version"],
                "artifact_id": mdef["artifact_id"],
                "artifact_version": mdef["version"],
                "artifact_path": mdef["artifact_path"],
                "manifest_path": mdef["manifest_path"],
                "status": mdef["status"],
                "trained": mdef["trained"],
                "evaluated": mdef["evaluated"],
                "production": mdef["production"],
                "experimental": mdef["experimental"],
                "is_quantum": mdef["quantum"],
                "quantum": mdef["quantum"],
                "qubit_count": mdef["qubit_count"],
                "raw_feature_count": mdef["raw_feature_count"],
                "classical_feature_count": mdef["classical_feature_count"],
                "quantum_feature_count": mdef["quantum_feature_count"],
                "dataset_version": mdef["dataset_version"],
                "pipeline_version": mdef["pipeline_version"],
                "score_semantics": mdef["score_semantics"],
                "probability_support": (mdef["family"] == "classical" and mdef["model_type"] != "hard_voting"),
                "explainability_support": mdef["explainability_support"],
                "evaluation_support": mdef["evaluation_support"],
                "selection_reason": mdef["selection_reason"],
                "selection_metric": mdef["selection_metric"],
            })

        return models_info


# Singleton service instance
ml_service = MLService()
